//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int ID { get; set; }
        public string MCode { get; set; }
        public string CCode { get; set; }
        public string SCode { get; set; }
        public string Title { get; set; }
        public string Prerequisites { get; set; }
        public int Semester_ID { get; set; }
        public int Year_ID { get; set; }
        public Nullable<System.DateTime> TimePeriodStart { get; set; }
        public Nullable<System.DateTime> TimePeriodEnd { get; set; }
        public int Credits { get; set; }
        public int LibArt_ID { get; set; }
    
        public virtual LibArt LibArt { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Year Year { get; set; }
    }
}
