//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Courses { get; set; }
        public bool IsMajor { get; set; }
        public int School_ID { get; set; }
    
        public virtual School School { get; set; }
    }
}
